### ISSUE TITLE
Font Looks strange

### ISSUE THREAD

**Issue by lloydroc** [pr0tocol/classyTouch_oh-my-zsh#2]
Hey using OS X with iTerm or Terminal the font looks weird and the cool little connectors with dots don't show up as dots but offset lines. There are also gaps in the lines.

What font do you recommend? Want to get this looking like you have it, what a great Theme!

Thanks,
Lloyd

**Comment by yarisgutierrez** [comment]
Hi Lloyd,

First, thanks for the comment -- really appreciate the feedback.

The font that's being use is a derivative of the Artwiz font _snap_ called _ohSnap_ which can be found here: https://sourceforge.net/projects/osnapfont

Hope this helps.

Thanks,

Yaris

**Comment by lloydroc** [comment]
Yes that does help. I think it would be great though if you put that in the README.md though. Since the average user (me) will install this cool theme and it won't look like it should.

I actually played around with it and went with one of those Power Line fonts "Fira Mono Medium from Powerline" which looks pretty cool.

**Comment by yarisgutierrez** [comment]
I'll ensure to update the README with these details. Thanks again.
